### ISSUE TITLE
Use with Smart-1 Cloud - does not work - ansible_api_key and ansible_cloud_mgmt_id are provided

### ISSUE THREAD

**Issue by mkol5222** [CheckPointSW/CheckPointAnsibleMgmtCollection#113]
- it works well with regular management server access using host, user and pass, but not with Smart-1 Cloud service

- **it fails for Smart-1 Cloud with unrelated error about missing _session_id on connection** when I add ansible_api_key, ansible_cloud_mgmt_id for correct S1C tenant hostname and comment out ansible_user and ansible_password in inventory variables

- I think it is expected this collection should work with Smart-1 Cloud assuming S1C tenant ID and API can be specified 

Would you suggest troubleshooting approach a data to collect, please?

Would you have verified minimal working sample project against Smart-1 Cloud I would use on my S1C tenant to check?

Thanks.

**Comment by chkp-edenbr** [comment]
Hi @mkol5222 ,

I understand this was a dependency issue in your collection and it was fixed.

Regards,
Eden

**Comment by mkol5222** [comment]
@chkp-edenbr you are correct. 

Issue was resolved by reinstalling Ansible with proper dependencies using

```
pipx install --include-deps ansible
ansible-galaxy collection install check_point.mgmt
```

vs installation process powered by Ubuntu's apt (that broke on _session_uid with S1C, probably due to different set of python dependencies)
```
sudo apt-add-repository ppa:ansible/ansible
sudo apt update
sudo apt install ansible -y
ansible-galaxy collection install check_point.mgmt
```

Issue resolved. Thank you.
