### ISSUE TITLE
check_point.mgmt.cp_mgmt_simple_cluster module and SIC

### ISSUE THREAD

**Issue by mminnen** [CheckPointSW/CheckPointAnsibleMgmtCollection#114]
I am using check_point.mgmt.cp_mgmt_simple_cluster module to create a cluster with two members.

When I create the resource the first time Ansible creates the cluster, the members and establishes the SIC using the one_time_password. If i make any changes to the existing resource using Ansible the resource is changes as desired, but the module also breaks the trust relationship (SIC).

So, the module can only be used once to create a cluster with trusted members, but cannot be used to maintain the config of these members.

It can be reproduces to use the simple cluster task and create the resource and members (with one_time_password per member specified). Then make a change e.g. the cluster color and re-run the playbook. After applying the change the SIC is broken.

**Comment by chkp-edenbr** [comment]
Hi @mminnen ,
Thanks for notifying us, we will take a look into it and update you.
Regards,
Eden

**Comment by chkp-edenbr** [comment]
Hi @mminnen 
Seems like a Management API issue rather than an Ansible collection bug, please open a ticket with checkpoint support.
Thanks,
Eden
