### ISSUE TITLE
Error with get_interfaces documentation

### ISSUE THREAD

**Issue by abrahamesc** [CheckPointSW/CheckPointAnsibleMgmtCollection#118]
There seems to be an issue with the documentation for the get_interfaces module.

![image](https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/assets/56666534/45a9fbe6-2c6f-48bc-a74f-ee2580115e61)

**Comment by chkp-edenbr** [comment]
Hi @abrahamesc ,
Which link are you using?
Bellow there's the documentation of this resource module in the latest collection version.
https://galaxy.ansible.com/ui/repo/published/check_point/mgmt/content/module/cp_mgmt_get_interfaces/?version=5.1.3
https://console.redhat.com/ansible/automation-hub/repo/published/check_point/mgmt/content/module/cp_mgmt_get_interfaces/

**Comment by abrahamesc** [comment]
I used: https://docs.ansible.com/ansible/latest/collections/check_point/mgmt/cp_mgmt_get_interfaces_module.html#ansible-collections-check-point-mgmt-cp-mgmt-get-interfaces-module

Thank you
