### ISSUE TITLE
Ansible Galaxy repository check_point.mgmt missing tags 5.2.0 and 5.2.1

### ISSUE THREAD

**Issue by cybercollector** [CheckPointSW/CheckPointAnsibleMgmtCollection#120]
Ansible Galaxy repository check_point.mgmt missing tags 5.2.0 and 5.2.1:
https://galaxy.ansible.com/ui/repo/published/check_point/mgmt/

**Comment by chkp-edenbr** [comment]
Currently there's an issue with uploading new versions to the Galaxy site, but they're available in the Automation-Hub and GitHub.
