### ISSUE TITLE
Community package requirements: sanity tests and repository management

### ISSUE THREAD

**Issue by gotmax23** [CheckPointSW/CheckPointAnsibleMgmtCollection#121]
# Community package requirements: sanity tests and repository management

(Note: This issue was filed in a semi-automated fashion. Let me know if you see errors in this issue.)

As per the [Ansible community package inclusion requirements][ci-testing], collections must pass `ansible-test sanity` tests. Version `5.1.1` of `check_point.mgmt`, corresponding to the `v5.1.1` tag in this repo, fails one or more of the required sanity tests.

The contents in the `v5.1.1` git tag do not match `check_point-mgmt-5.1.1.tar.gz` as uploaded to Ansible Galaxy. For future releases, please make sure that the contents uploaded to Galaxy match the sources that were tagged as that release. See the [Repository management requirements][repo-mgmt] for more information.

Please see the errors below and address them. If these issues aren't addressed within a reasonable time period, the collection may be subject to [removal from Ansible][removal].

Thank you for your efforts and for being part of the Ansible package! We appreciate it.

---

## Sanity tests

The following tests were run using `ansible-test` version `2.16.1`:

- ansible-doc
- compile
- validate-modules
- yamllint

Note that this is only a subset of the required sanity tests. Please make sure you run them in all in your CI.

### Results

**Issue truncated. [Click here to read more](https://gist.github.com/gotmax23/3b6aad072174d391265414c549a8b0b8)**.

[ci-testing]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#ci-testing
[repo-mgmt]: https://docs.ansible.com/ansible/latest/community/collection_contributors/collection_requirements.html#repository-management
[removal]: https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst

**Comment by chkp-edenbr** [comment]
Fixed in v5.2.2
