### ISSUE TITLE
Invalid Calls To logout API Endpoint While Using Ansible Check Point Collection (Check_Point.Mgmt)

### ISSUE THREAD

**Issue by gabhishek627** [CheckPointSW/CheckPointAnsibleMgmtCollection#137]
- Ansible generates dummy calls to the target Check Point platform, these calls are getting rejected every time with response 400, but it consumes resources.

- check_point.mgmt collection version 6.1.0

**Comment by chkp-edenbr** [comment]
Hi @gabhishek627,
Which calls are they? Can you share the logs ($MDS_FWDIR/log/api.elg) and your playbook?
Regards
