### ISSUE TITLE
"show-.." commands via api_command() should not fail with discard_and_fail()

### ISSUE THREAD

**Issue by duanetoler** [CheckPointSW/CheckPointAnsibleMgmtCollection#139]
In module_utils/checkpoint.py, when api_command() is called from a "show_..." module and when error_code != 200, it should not fail with discard_and_fail().  The command is just a "show".  This should fail like api_call_facts() without a discard.

**Comment by chkp-edenbr** [comment]
Hi @duanetoler ,
Will take this into consideration in the next version.
Regards

**Comment by duanetoler** [comment]
Thanks!  Would it be helpful if I made a PR for the patch I made?

**Comment by chkp-edenbr** [comment]
Hi @duanetoler ,
This is an open source collection, creating a PR would be great.
Regards

**Comment by duanetoler** [comment]
PR #148 is ready
