### ISSUE TITLE
cp_mgmt_administrator: expiration_date not updating

### ISSUE THREAD

**Issue by alex-barth** [CheckPointSW/CheckPointAnsibleMgmtCollection#15]
When expiration_date is the only changed value, ansible returns with "ok".
It should detect the change, replace the value and report "changed".

**Comment by chkp-orso** [comment]
Hi @alex-barth 

Can you please send the playbook, and the output of running this playbook
Also which version of the collection do you have?

Thanks, Or

**Comment by chkp-orso** [comment]
@alex-barth Thanks!
I've found the bug, it will be fixed in the next version
