### ISSUE TITLE
Couldn't resolve module/action 'cp_mgmt_nat_rule'.

### ISSUE THREAD

**Issue by doritoes** [CheckPointSW/CheckPointAnsibleMgmtCollection#150]
Using check_point.mgmt 6.2.1 (current) in practicing my automation skills I learned in Tim's  CCAS class. Ansible 2.10 on WSL running Ubuntu 22.04 Also manually updated to Ansible 2.16.

Able to use many modules in my ansible playbooks but some fail. This makes this a puzzle because the other things work fine: cp_mgmt_host, cp_mgmt_network, cp_mgmt_address_range, cp_mgmt_package, cp_mgmt_access_rule, cp_mgmt_publish

`ERROR! couldn't resolve module/action 'cp_mgmt_nat_rule'. This often indicates a misspelling, missing collection, or incorrect module path.`

https://galaxy.ansible.com/ui/repo/published/check_point/mgmt/content/module/cp_mgmt_nat_rule/?keywords=nat&version=6.2.1

Other example is cp_mgmt_access_section. I haven't tried any additional methods.

Example task that fails
`
    - name: add a NAT rule
      cp_mgmt_nat_rule:
        package: Lab_Policy
        name: Outbound NAT
        enabled: true
        installed_on:
        - Policy Targets
        original_destination: All_Internet
        original_source: branch1_lan
        translated_source: branch1_outbound_nat
        method: hide
        position: top
        comments: outbound NAT
        state: present
`

Phoneboy noted The documentation for cp_mgmt_nat_rule says: Minimum version required is 1.7.1 and JHF with PMTR-88097. This corresponds to API version 1.7.1, which is R81. The first JHF with PMTR-88097 is Take 82.

SMS is R81.20 installed from Check_Point_R81.20_T634.iso, and installed JHF 84. Issue still occurs.

There is how I set up ansible and check_point.mgmt on the WSL system running Ubuntu 22.04
- Remove default version
  - `sudo apt remove ansible`
  - `sudo apt --purge autoremove`
- Set up PPA support
  - `sudo apt install -y software-properties-common`
  - `sudo apt-add-repository ppa:ansible/ansible`
- Install latest version of Ansible
  - `sudo apt update && sudo apt install -y ansible`
  - `ansible --version`
- Install the Ansible collections
  - `ansible-galaxy collection install community.general vyos.vyos check_point.mgmt check_point.gaia`

Here is my complete process and how I build the lab using automation:
https://github.com/doritoes/NUC-Labs/blob/xcp-ng-improvement/XCP-ng/Appendix-Ansible.md

No related messages in $FWDIR/api.elg as this error is in check_point.mgmt

**Comment by chkp-edenbr** [comment]
Hi @doritoes,
I wasn't able to recreate the issue, seems like it might be an issue with your playbook, here's a usage example, make sure you've written the resource module path as so check_point.mgmt.cp_mgmt_nat_rule

  tasks:
    - name: add nat
      **check_point.mgmt.cp_mgmt_nat_rule**:
        position: bottom
        package: "Standard"
        name: example
        auto_publish_session: true

**Comment by doritoes** [comment]
@chkp-edenbr thank you for the speedy reply.

Prepending every module with `check_point.mgmt` works to resolve this issue.

examples:
- check_point.mgmt.cp_mgmt_package
- check_point.mgmt.cp_mgmt_access_rule
- check_point.mgmt.cp_mgmt_access_section
- check_point.mgmt.cp_mgmt_publish

This is extra work, but eliminates the problem of your task using different repos for different tasks.

For those who experience my issue on Ubuntu 22.04:
- don't install the default ansible; install from the ppa to get a current version of Ansible
- i got an older API version with `ansible-galaxy collection install check_point.mgmt`; use  `ansible-galaxy collection install --force check_point.mgmt`; to get the latest version

**Comment by doritoes** [comment]
Not a bug; opportunity to improve documentation

**Comment by chkp-edenbr** [comment]
Our README contains usage examples as well as each resource module in our collection which you might find helpful.
