### ISSUE TITLE
"msg": "Could not find imported module support code for cp_mgmt_access_section

### ISSUE THREAD

**Issue by sinu** [CheckPointSW/CheckPointAnsibleMgmtCollection#16]
@chkp-orso @chkp-adamr @chkp-mostafaw @chkp-michaele 
when i am using cp_mgmt_access_section this module, i am getting the following error, do you have any idea 
{
    "msg": "Could not find imported module support code for cp_mgmt_access_section.  Looked for either api_call.py or checkpoint.py",
    "_ansible_no_log": false
}

**Comment by chkp-orso** [comment]
Hi,
please see in this path: CheckPointAnsibleMgmtCollection/plugins/modules/cp_mgmt_access_section.py
version 1.0.5

Thanks,
Or
