### ISSUE TITLE
generic_err_invalid_parameter_name', 'message': 'Unrecognized parameter'

### ISSUE THREAD

**Issue by EnzovdWetering** [CheckPointSW/CheckPointAnsibleMgmtCollection#161]
Hi there,

I'm trying to get the entire rulebase using cp_mgmt_access_rule_facts, howerver I keep running into issues where I get Unrecognized parameter errors as can be seen below.

**This config:**
- name: show-access-rulebase
  cp_mgmt_access_rule_facts:
    details_level: standard
    limit: 20
    name: mypolicy Network
    offset: 0
    use_object_dictionary: true
  vars:
    ansible_user: '{{ check_point_prd_username }}'
    ansible_password: '{{ check_point_prd_password }}'
    ansible_checkpoint_domain: '{{ extvar_cpdomain }}'
  register: result
  tags:
    - cp_mgmt_access_rule_facts

**Give this result**
fatal: [w.x.y.z]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dereference_group_members": null,
            "details_level": "standard",
            "filter": null,
            "filter_settings": null,
            "hits_settings": null,
            "layer": null,
            "limit": 20,
            "name": "mypolicy Network",
            "offset": 0,
            "order": null,
            "package": null,
            "show_as_ranges": null,
            "show_hits": null,
            "show_membership": null,
            "use_object_dictionary": true,
            "version": null
        }
    },
    "msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter_name', 'message': 'Unrecognized parameter [limit]'}"
}

When I remove the limit parameter, I get a new error:
"msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter_name', 'message': 'Unrecognized parameter [offset]'}"

When I remove the offset parameter, I get a new error:
"Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter_name', 'message': 'Unrecognized parameter [use-object-dictionary]

When I remove the use-object-dictionary, I get a new error:
"Checkpoint device returned error 400 with message {'code': 'generic_err_missing_required_parameters', 'message': 'Missing parameter: [layer]'}"

When I add the layer parameter and the config becomes:
- name: show-access-rulebase
  cp_mgmt_access_rule_facts:
    details_level: standard
    name: 'mypolicy Network'
    layer: 'mypolicy Network'
  vars:
    ansible_user: '{{ check_point_prd_username }}'
    ansible_password: '{{ check_point_prd_password }}'
    ansible_checkpoint_domain: '{{ extvar_cpdomain }}'
  register: result
  tags:
    - cp_mgmt_access_rule_facts

And then I get this error:
"msg": "Checkpoint device returned error 400 with message {'code': 'generic_error', 'message': 'Runtime error: com.checkpoint.management.access.objects.access_rulebase.AccessCtrlRulebase incompatible with com.checkpoint.objects.rulebase.RulebaseRule'}"

When I remove the name parameter, I get this new error:
 "msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_missing_required_parameters', 'message': 'Missing parameter: [uid or rule-number or name]'}"

I've also tried setting name to null or '' but neither works.

The ansible galaxy collection version is  check_point.mgmt 6.2.1 
The API version of the Check Point Management Server is 1.9.1

Note: One thing that does work is using the access_rule_facts to get a single rulebaserule. Using the name and layer parameters, however that is not what I'm looking for. I would like to get the entire rulebase. What I find really strange is that the parameters that it is complaining about, are actually all documented at 

https://galaxy.ansible.com/ui/repo/published/check_point/mgmt/content/module/cp_mgmt_access_rule_facts/?version=6.2.1.. 

I could be wrong, but it feels like it is using the show-access-rule API endpoint instead of the show-access-rulebase API behind the scenes.

**Comment by chkp-edenbr** [comment]
Hi @EnzovdWetering ,
Two fixes were added to this repository and will be available in the upcoming version.
https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/commit/c2089f75451e9dd69dc8f577709e16fa5abd4778
https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/commit/9c00e1105c7911a7baa01e3c15a9bed1cb967373

**Comment by EnzovdWetering** [comment]
Awesome! 

Thx @chkp-edenbr 

Can you give an estimate when the new version is released? Than I can plan accordingly.
 
Best regards,
Enzo

**Comment by chkp-edenbr** [comment]
Hi,
Should be released approximately by the end of January.

**Comment by pbousek** [comment]
Hello,
I'm using 
Collection                               Version
---------------------------------------- -------
check_point.mgmt                         6.4.0 

it contain mentioned patches, but I still get

    "msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter_name', 'message': 'Unrecognized parameter [limit]'}"

any idea?

Thanks
Petr
