### ISSUE TITLE
policypakage selection in cp_mgmt_access_rule

### ISSUE THREAD

**Issue by sinu** [CheckPointSW/CheckPointAnsibleMgmtCollection#18]
Hello @chkp-orso, @chkp-mostafaw @chkp-adamr @justjais @chkp-michaele 

in old version we had an parameter to specify the policy package name in checkpoint_access_rule, but how do we achieve this in new version cp_mgmt_access_rule

```  - name: Create access rule
    checkpoint_access_rule:
      layer: security
      name: "{{ policyname }}"
      position: top
      source: "{{ srcaddr_updated }}"
      destination: "{{ dstaddr_updated }}"
      action: "{{ action }}"
      service: "{{ servicename_updated }}"
      policy_package: "{{ pkgname }}"
      auto_install_policy: yes
      auto_publish_session: yes
      state: present
```

**Comment by chkp-orso** [comment]
Hi @sinu ,

Thanks for reaching us.

The parameter "layer" will indicate which layer the rule is placed.
And the layer name is unique, so it will be clear in which package the layer is in.

Thanks,
Or
