### ISSUE TITLE
Error in running mgmt_threat_indicator

### ISSUE THREAD

**Issue by antman111** [CheckPointSW/CheckPointAnsibleMgmtCollection#20]
Hi, 

I am trying to add threat indicator via ansible and it gives me error when i run the playbook ( check mode is working fine) 

![error](https://user-images.githubusercontent.com/67148739/85124717-f2e43980-b25c-11ea-8daa-29ad3c1dfc61.JPG)

the management server is running R80.40 and permission use is admin permission. Thank you.

**Comment by antman111** [comment]
This is the api.elg log of management server  when run the playbook.
![error1](https://user-images.githubusercontent.com/67148739/85159353-fba23300-b28f-11ea-814a-cf57aebea008.JPG)

Seem something to do with illegal argument but i am not sure where is the wrong exactly.

**Comment by chkp-orso** [comment]
@antman111 Thank you!
We found a bug inthis module.
will update once solved :)
