### ISSUE TITLE
Still unable to set Gateway Platform Version

### ISSUE THREAD

**Issue by b4eri** [CheckPointSW/CheckPointAnsibleMgmtCollection#23]
Hi chkp-orso,

we still have this issue with the collection 1.0.5.

`
fatal: [CPM]: FAILED! => {"changed": false, "msg": "Checkpoint device returned error 400 with message {u'message': u'Unknown API version: R80.30', u'code': u'err_unknown_api_version'}"}
`

Any recommendations?

Thanks. @chkp-orso

_Originally posted by @b4eri in https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/issues/1#issuecomment-655404418_

**Comment by b4eri** [comment]
what I see is that "version" changed to "gateway_version" in collection 1.0.5 but mgmt_cli 1.6 won't recognize that param.

**Comment by chkp-orso** [comment]
That's right.
The name is different between the mgmt_cli and this collection, due to different meaning in Ansible..
