### ISSUE TITLE
Missing meta data

### ISSUE THREAD

**Issue by sarigs** [CheckPointSW/CheckPointAnsibleMgmtCollection#25]
Dear Developer, 

 For readability and Search Engine Optimization (SEO) it would be great if you could do the followings:
- [ ] Please provide more than 8 words in the "About" field
- [ ] Please provide relevant "Topics" 
>**Environment topic examples**:
>azure, aws, gcp
>**Functionality topic examples**:
>**build**, **deploy**, **staging**, **operate**, terraform, ansible, helm, android, cloudguardIaaS, management, gaia, threat-prevention, identity-awareness, smp, iot, cloudguard-connect, cloudguard-dome9, malware, evasion

**Comment by chkp-orso** [comment]
Hi @sarigs ,
Where is the "About" field?
And where is the Topics?

Thanks,
Or

**Comment by chkp-orso** [comment]
Updated
