### ISSUE TITLE
Allow session level name/comment/description

### ISSUE THREAD

**Issue by it-ic** [CheckPointSW/CheckPointAnsibleMgmtCollection#28]
Please allow setting a name, comment and description during session login. (so these are reflected in the revisions overview)

Available in the API as per:
https://sc1.checkpoint.com/documents/latest/APIs/#web/login~v1.6.1%20

session-comments | string | Session comments. Can be viewed only using the show-session API.
session-description | string | A description of the session's purpose.
session-name | string | Session unique name.

![image](https://user-images.githubusercontent.com/52914044/91424788-8e47eb00-e85a-11ea-8adb-5986d77e7b7a.png)

**Comment by chkp-orso** [comment]
Hi,

Thanks for reaching us.

We will investigate and see if it's possible to add those fields in Ansible.

Thanks,
Or

**Comment by Arenaos** [comment]
> Hi,
> 
> Thanks for reaching us.
> 
> We will investigate and see if it's possible to add those fields in Ansible.
> 
> Thanks,
> Or

Have you find a solution ? We have the option to force the description for each publish on our smartconsole. Impossible to publish with ansible.

Gary
