### ISSUE TITLE
cp_mgmt_access_rule: Policy position in section not possible

### ISSUE THREAD

**Issue by r33net** [CheckPointSW/CheckPointAnsibleMgmtCollection#33]
The Modul **cp_mgmt_access_rule** it is not possible to place the rule in top or bottom of a specific section identified by uid or name or before and after specific section/rule identified by uid or name. You can only place it in the top, bottom of the ruleset or at a specific rule number. 
This problem is only in ansible. the web api (mgmt_cli) can position the rule in a section or abovce/below a rule. 
https://sc1.checkpoint.com/documents/latest/APIs/#web/add-access-rule~v1.7%20

**I think this is absolutely necessary to use the Ansible CheckPoint module productively.** 

     - name: create access rule
       check_point.mgmt.cp_mgmt_access_rule:
        layer: Network        
        name: MyRule    
        position: 
          top: "MySectionTitle"
        source: "host_10.11.11.2"
        destination: "host_10.11.11.3"
        service:
          - ssh_version_2
        action: accept
        comments: "MyComment"
        auto_publish_session: true

PLAY [Test Playbook] ***********************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************
ok: [1.2.3.3]

TASK [create access rule] ******************************************************************************************************************************************
[WARNING]: The value {'top': 'MySectionTitle'} (type dict) in a string field was converted to "{'top': 'MySectionTitle'}" (type string). If this does not look like
what you expect, quote the entire value to ensure it does not change.
fatal: [1.2.3.4]: FAILED! => {"changed": false, "msg": "Checkpoint device returned error 400 with message {'code': 'generic_err_invalid_parameter', 'message': \"Invalid parameter for [position]. The invalid value [{'top': 'MySectionTitle'}] should be replaced by one of the following values: [top, bottom]\"} Unpublished changes were discarded"}

PLAY RECAP *********************************************************************************************************************************************************
1.2.3.4                : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by chkp-orso** [comment]
Hi,

Thanks for reaching us.

We intentionally removed the first three options because it damages one of Ansible requirements for idempotency.

Thanks,
Or

**Comment by fad3t** [comment]
Hi,

I was also looking for this option - top/bottom isn't enough in our case.
What about ignoring the position argument when the rule already exists (= update)?

Thanks,
Fred

**Comment by jsalatiel** [comment]
Also looking for this option.
I think  ignoring the position argument when the rule already exists (= update) would be enough.
