### ISSUE TITLE
Feature request: Ansible modules

### ISSUE THREAD

**Issue by padavrexi** [CheckPointSW/CheckPointAnsibleMgmtCollection#34]
Hi,

Several functions aren't yet available in the Ansible collection even though they do exist as Management API endpoints. Namely, the ability to create, read, update, and delete the following:

1. **cluster** (`xxx-simple-cluster` API endpoints)
2. **updatable objects** (`show updatable-objects-repository-content, update-updatable-objects-repository-content, xxx-updatable-object` API endpoints)
3. **data center** (`xxx-data-center-server `API endpoints)
4. **IPS update schedule** (`xxx-ips-update-schedule `API endpoints)

Running on **check_point.mgmt version 2.0.0**
```
$ ansible-galaxy collection list
# /home/kallergisn/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
ansible.netcommon    1.3.0
ansible.posix        1.1.1
azure.azcollection   1.1.0
check_point.mgmt     2.0.0
community.general    1.2.0

```

**Comment by chkp-orso** [comment]
Hi,

Thanks for reaching us.

We plan to add the modules in future versions.

Thanks,
Or
