### ISSUE TITLE
Add Object to Existing Group

### ISSUE THREAD

**Issue by brookzbj** [CheckPointSW/CheckPointAnsibleMgmtCollection#35]
Apologies if this is the wrong location... I'm attempting to add a network object to an existing object group however the existing group module does not seem to provide this. It replaces the existing members with whatever members is present in the playbook. Is there an option I'm missing?

**Comment by chkp-orso** [comment]
Hi @brookzbj 
Sorry, unfortunately  we don't provide such behavior since it's damage one of Ansible requirement.
You can use the group_facts, to get the list, and then if you want to add/remove you give the list +/- the network to remove..
