### ISSUE TITLE
Session disconnected before publish is called

### ISSUE THREAD

**Issue by ygo74** [CheckPointSW/CheckPointAnsibleMgmtCollection#36]
Context :

- Checkpoint Collection : 2.0.0
- Ansible 2.10.3 with Python 3.6

Run playbooks to 10 CMAs (9 within Multi-Domain and 1 in standalone)

Execute within a loop (for 395 objects) :
- name: Add or configure subnet object
  check_point.mgmt.cp_mgmt_network:
    name:        '{{ firewall_cp_network_object.name }}'
    subnet:      '{{ firewall_cp_network_object.address }}'
    subnet_mask: '{{ firewall_cp_network_object.netmask }}'
    comments:    '{{ firewall_cp_network_object.desc }}'
    color:       'black'
    state:       present
    auto_publish_session: no
    ignore_warnings: yes

  loop: '{{ firewall_cp_networks_subnets_list }}'

  loop_control:
    loop_var: 'firewall_cp_network_object'
    label:    '{{ firewall_cp_network_object.name }}'

+
Execute within a loop for (195 objects) :
- name: Add or configure network group
  check_point.mgmt.cp_mgmt_group:
    members:  '{{ firewall_cp_network_object.members }}'
    name:     '{{ firewall_cp_network_object.name    }}'
    comments: '{{ firewall_cp_network_object.comment }}'
    color:    'black'
    state:    present
    auto_publish_session: no

  loop: '{{ firewall_cp_networks_groups_list }}'

  loop_control:
    loop_var: 'firewall_cp_network_object'
    label:    '{{ firewall_cp_network_object.name }}'

+
# Publish modifications in the CMA
- name: Publish firewall changes
   check_point.mgmt.cp_mgmt_publish:

the session has been disconnected between "Add or configure subnet object" and "Add or configure network group".

when we executed this playbook to only one CMA, there is no session disconnected so we can publish all changes. But with multiple CMAs in the playbook, sessions are disconnected

**Comment by chkp-orso** [comment]
@ygo74 
Sorry we don't support the ability to login with multiple sessions in parallel (before publish).
