### ISSUE TITLE
Access-rulebase facts over Ansible module ?

### ISSUE THREAD

**Issue by JBaptisme33** [CheckPointSW/CheckPointAnsibleMgmtCollection#4]
hello guys,

Thanks for your work and modules.
Is there a way to access to access-rulebase over an existing Ansible module ?

Indeed, module to obtain access-rulebase facts semms to existing ?
With actual modules, how to compare existing ruleset with a new one we want to add ?

Thanks :)

**Comment by chkp-orso** [comment]
Hi, Thanks :)

For **showing** the rulebase we have the module you mentioned "cp_mgmt_access_rule_facts.py".
And for **changing** access rules we have the module "cp_mgmt_access_rule.py"
And for comparing you can use the first module I mentioned, or just change the rulebase with the second module I mentioned, and see in the output of the playbook if the rulebase was changed.

Thanks , Or
