### ISSUE TITLE
ConnectionError: string indices must be integers\n"

### ISSUE THREAD

**Issue by vietde** [CheckPointSW/CheckPointAnsibleMgmtCollection#41]
I am new to Ansible and following all the requirement. I tried to run playbook, it keeps giving me this error. Any idea?

`osboxes@osboxes:~/Ansible$ ansible-playbook -i allhost.yml CP_Add_Host.yml --ask-pass -vvv
ansible-playbook 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/osboxes/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Using /etc/ansible/ansible.cfg as config file
SSH password:
host_list declined parsing /home/osboxes/Ansible/allhost.yml as it did not pass its verify_file() method
script declined parsing /home/osboxes/Ansible/allhost.yml as it did not pass its verify_file() method
Parsed /home/osboxes/Ansible/allhost.yml inventory source with yaml plugin

PLAYBOOK: CP_Add_Host.yml ************************************************************************************************************************************************************************************************************************************
1 plays in CP_Add_Host.yml

PLAY [checkpoint] ********************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************************************
task path: /home/osboxes/Ansible/CP_Add_Host.yml:4
<10.10.10.2> ESTABLISH LOCAL CONNECTION FOR USER: osboxes
<10.10.10.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559 `" && echo ansible-tmp-1624252401.3097262-252417755086559="` echo /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559 `" ) && sleep 0'
<checkpoint> Attempting python interpreter discovery
<10.10.10.2> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.10.10.2> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/system/setup.py
<10.10.10.2> PUT /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/tmpwkcwdj63 TO /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559/AnsiballZ_setup.py
<10.10.10.2> EXEC /bin/sh -c 'chmod u+x /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559/ /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559/AnsiballZ_setup.py && sleep 0'
<10.10.10.2> EXEC /bin/sh -c '/usr/bin/python3 /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559/AnsiballZ_setup.py && sleep 0'
<10.10.10.2> EXEC /bin/sh -c 'rm -f -r /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252401.3097262-252417755086559/ > /dev/null 2>&1 && sleep 0'
ok: [checkpoint]
META: ran handlers

TASK [Adding Site2] ******************************************************************************************************************************************************************************************************************************************
task path: /home/osboxes/Ansible/CP_Add_Host.yml:8
<10.10.10.2> ESTABLISH LOCAL CONNECTION FOR USER: osboxes
<10.10.10.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985 `" && echo ansible-tmp-1624252402.8120823-198978239206985="` echo /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985 `" ) && sleep 0'
Using module file /usr/lib/python3/dist-packages/ansible/modules/network/check_point/cp_mgmt_host.py
<10.10.10.2> PUT /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/tmpjq96ht27 TO /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py
<10.10.10.2> EXEC /bin/sh -c 'chmod u+x /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/ /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py && sleep 0'
<10.10.10.2> EXEC /bin/sh -c '/usr/bin/python3 /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py && sleep 0'
<10.10.10.2> EXEC /bin/sh -c 'rm -f -r /home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py", line 102, in <module>
    _ansiballz_main()
  File "/home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.network.check_point.cp_mgmt_host', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/modules/network/check_point/cp_mgmt_host.py", line 333, in <module>
  File "/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/modules/network/check_point/cp_mgmt_host.py", line 328, in main
  File "/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/network/checkpoint/checkpoint.py", line 199, in api_call
  File "/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/network/checkpoint/checkpoint.py", line 56, in send_request
  File "/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: string indices must be integers
fatal: [checkpoint]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/osboxes/.ansible/tmp/ansible-local-3310dt8vaq_8/ansible-tmp-1624252402.8120823-198978239206985/AnsiballZ_cp_mgmt_host.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.network.check_point.cp_mgmt_host', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/modules/network/check_point/cp_mgmt_host.py\", line 333, in <module>\n  File \"/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/modules/network/check_point/cp_mgmt_host.py\", line 328, in main\n  File \"/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/network/checkpoint/checkpoint.py\", line 199, in api_call\n  File \"/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/network/checkpoint/checkpoint.py\", line 56, in send_request\n  File \"/tmp/ansible_cp_mgmt_host_payload_rs3m7mty/ansible_cp_mgmt_host_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: string indices must be integers\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************************************
checkpoint                 : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
**`**

**Comment by chkp-orso** [comment]
@vietde Hi, please provide the playbook and the hosts file

**Comment by BarrieAlmond** [comment]
Hi,

I also have been receiving this error. My playbook works fine on a standalone Ansible 2.9.6 box, but I am trying to use AWX v19.2.2 (open source Ansible Tower) with an execution environment running Ansible 2.10.11. It doesn't work with the out of the box Ansible 2.11 execution environment either.

I have my host set up in the GUI with the following vars:

```
ansible_host: <IP address>
ansible_network_os: check_point.mgmt.checkpoint
ansible_httpapi_use_ssl: True
ansible_httpapi_validate_certs: False
```

My playbook is:

```
- name: Search Checkpoint for objects
  hosts: <server name>
  connection: ansible.netcommon.httpapi
  gather_facts: false

  collections:
    - check_point.mgmt

  tasks:
   - name: Get Checkpoint objects
      check_point.mgmt.checkpoint_object_facts:
        object_filter: "test"
        object_type: "host"
```

The error log is:

```
ansible-playbook 2.10.11
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.6 (default, Jan 29 2021, 17:38:16) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
No config file found; using defaults
SSH password: 
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with script plugin
Loading collection check_point.mgmt from /runner/requirements_collections/ansible_collections/check_point/mgmt
Loading callback plugin awx_display of type stdout, v2.0 from /usr/local/lib/python3.8/site-packages/ansible_runner/callbacks/awx_display.py
Skipping callback 'awx_display', as we already have a stdout callback.
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: checkpoint_test.yml **************************************************
Positional arguments: test/general/checkpoint_test.yml
verbosity: 4
ask_pass: True
remote_user: <username>
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/runner/inventory/hosts',)
extra_vars: ('@/runner/env/tmpq2k52069', '@/runner/env/tmpeb6719qe', '@/runner/env/extravars')
forks: 5
1 plays in test/general/checkpoint_test.yml

PLAY [Search Checkpoint for objects] *******************************************
META: ran handlers

TASK [Get Checkpoint objects based on decom list] ******************************
task path: /runner/project/test/general/checkpoint_test.yml:9
Loading collection ansible.netcommon from /runner/requirements_collections/ansible_collections/ansible/netcommon
<IP address> attempting to start connection
<IP address> using connection plugin ansible.netcommon.httpapi
Found ansible-connection at path /usr/local/bin/ansible-connection
<IP address> local domain socket does not exist, starting it
<IP address> control socket path is /home/runner/.ansible/pc/e1028e1d8b
<IP address> Loading collection ansible.netcommon from /runner/requirements_collections/ansible_collections/ansible/netcommon
<IP address> Loading collection check_point.mgmt from /runner/requirements_collections/ansible_collections/check_point/mgmt
<IP address> local domain socket listeners started successfully
<IP address> loaded API plugin ansible_collections.check_point.mgmt.plugins.httpapi.checkpoint from path /runner/requirements_collections/ansible_collections/check_point/mgmt/plugins/httpapi/checkpoint.py for network_os check_point.mgmt.checkpoint
<IP address> 
<IP address> local domain socket path is /home/runner/.ansible/pc/e1028e1d8b
<IP address> ESTABLISH LOCAL CONNECTION FOR USER: runner
<IP address> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/runner/.ansible/tmp/ansible-local-193ftglv7h `"&& mkdir "` echo /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047 `" && echo ansible-tmp-1625151234.6511328-24-57509880931047="` echo /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047 `" ) && sleep 0'
<server name> Attempting python interpreter discovery
<IP address> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<IP address> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /runner/requirements_collections/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py
<IP address> PUT /home/runner/.ansible/tmp/ansible-local-193ftglv7h/tmpjw3egmsp TO /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py
<IP address> EXEC /bin/sh -c 'chmod u+x /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/ /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py && sleep 0'
<IP address> EXEC /bin/sh -c '/usr/bin/python /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py && sleep 0'
<IP address> EXEC /bin/sh -c 'rm -f -r /home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.check_point.mgmt.plugins.modules.checkpoint_object_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py", line 126, in <module>
  File "/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py", line 113, in main
  File "/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py", line 95, in get_object
  File "/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible/module_utils/connection.py", line 195, in __rpc__
ansible.module_utils.connection.ConnectionError: string indices must be integers
[DEPRECATION WARNING]: Distribution centos 8 on host server name should use 
/usr/libexec/platform-python, but is using /usr/bin/python for backward 
compatibility with prior Ansible releases. A future Ansible release will 
default to using the discovered platform python for this host. See https://docs
.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for 
more information. This feature will be removed in version 2.12. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [server name]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\\n  File \\"/home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py\\", line 102, in <module>\\n    _ansiballz_main()\\n  File \\"/home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py\\", line 94, in _ansiballz_main\\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\\n  File \\"/home/runner/.ansible/tmp/ansible-local-193ftglv7h/ansible-tmp-1625151234.6511328-24-57509880931047/AnsiballZ_checkpoint_object_facts.py\\", line 40, in invoke_module\\n    runpy.run_module(mod_name='ansible_collections.check_point.mgmt.plugins.modules.checkpoint_object_facts', init_globals=None, run_name='__main__', alter_sys=True)\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 207, in run_module\\n    return _run_module_code(code, init_globals, run_name, mod_spec)\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 97, in _run_module_code\\n    _run_code(code, mod_globals, init_globals,\\n  File \\"/usr/lib64/python3.8/runpy.py\\", line 87, in _run_code\\n    exec(code, run_globals)\\n  File \\"/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py\\", line 126, in <module>\\n  File \\"/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py\\", line 113, in main\\n  File \\"/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible_collections/check_point/mgmt/plugins/modules/checkpoint_object_facts.py\\", line 95, in get_object\\n  File \\"/tmp/ansible_check_point.mgmt.checkpoint_object_facts_payload_ljbwj35q/ansible_check_point.mgmt.checkpoint_object_facts_payload.zip/ansible/module_utils/connection.py\\", line 195, in __rpc__\\nansible.module_utils.connection.ConnectionError: string indices must be integers\\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *********************************************************************
server name                   : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

**Comment by BarrieAlmond** [comment]
@chkp-orso  I just wondered if you had any thoughts on this issue?

**Comment by Jasperswaagman** [comment]
@BarrieAlmond did you get this working in the end?

**Comment by BarrieAlmond** [comment]
@Jasperswaagman In the end I gave up with the Checkpoint collection and used pure API calls. This was a year ago and the issues that I had were with version 2.0.0 of the collection. I see that there have been a number of updates since so it's possible that the issue no longer exists.

**Comment by Jasperswaagman** [comment]
@BarrieAlmond (and possible others). I've managed to get it working. It seems I was using the wrong ports in the end. A good reminder that `ansible_port` and `ansible_httpapi_port` are different.
