### ISSUE TITLE
[Feature Request] Add support for new_name parameter in many modules

### ISSUE THREAD

**Issue by edeka-spatt** [CheckPointSW/CheckPointAnsibleMgmtCollection#47]
I need to rename objects, the API has the parameter new_name for this. However the ansible modules are missing this parameter.

For instance in cp_mgmt_network.py there is an example for new_name but the module is missing it.

**Comment by chkp-shirango** [comment]
Hi @edeka-spatt,

We do not support object renaming because the object name uses as an object identifier.

Thanks,
Shiran
