### ISSUE TITLE
cp_mgmt_access_rule - position does not support API functionality

### ISSUE THREAD

**Issue by writememe** [CheckPointSW/CheckPointAnsibleMgmtCollection#5]
In the Checkpoint API documentation for adding the access rule (https://sc1.checkpoint.com/documents/latest/APIs/#cli/add-access-rule~v1.3%20), the `position` parameter exposes both `below` and `above` as well as `top` and `bottom`.

The ansible-galaxy module [cp_mgmt_access_layer.py](https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/blob/master/plugins/modules/cp_mgmt_access_layer.py), does not offer the `below` and `above` functionality.

Is it possible to have this functionality exposed?

Thanks
![Checkpoint-position-API](https://user-images.githubusercontent.com/24688622/75306510-6f619f80-589d-11ea-805f-7c0433dcea16.PNG)

**Comment by chkp-orso** [comment]
Hi Daniel,

Sorry but We intentionally removed this functionality because it damages one of Ansible requirements for idempotency.

Thanks, Or

**Comment by writememe** [comment]
Hi Or,

Thanks for getting back to me, it's understandable and makes sense.
