### ISSUE TITLE
ConnectionError for check_point.mgmt.cp_mgmt_access_rule

### ISSUE THREAD

**Issue by tslro** [CheckPointSW/CheckPointAnsibleMgmtCollection#50]
We have the issue that check_point.mgmt.cp_mgmt_access_rule is taking a long time when we call cp_mgmt_access_rule for updating an existing rule. By increasing the command_timeout we were able to resolve the timeout problem but the performance of the script itself will decrease a lot as longer as the rulebase will be. Currently we tried replacing a rule inside a ruleset that has about 700 rules and it took 90 seconds. Replacing multiple rules inside larger policies will take a lot of time.

Why is cp_mgmt_access_rule depending so heavily on the size of the rulebase and what are the possibilities for speeding up the process?

Thank you for any kind of suggestions.

**Comment by chkp-shirango** [comment]
Hi @tslro,

Can you please send me the api.csv and the api.elg log files to my email?
shirango@checkpoint.com

Thanks,
Shiran
