### ISSUE TITLE
Run script module - error/bug

### ISSUE THREAD

**Issue by BrunoJorge21** [CheckPointSW/CheckPointAnsibleMgmtCollection#51]
Versions:
 - ansible core: 2.11.3
 - checkpoint_point-mgmt: 2.2.0
 - python: 3.9.2

Playbook:
![Playbook](https://user-images.githubusercontent.com/79717068/148371698-d7ecd309-1046-48ca-8e84-3582be092499.PNG)

Inventory:
![Inventory](https://user-images.githubusercontent.com/79717068/148371735-2efcb886-6d24-4b17-8897-604ee09fcbc8.PNG)

Output:
![Output_ansible](https://user-images.githubusercontent.com/79717068/148371765-e79f18be-7e8e-4764-9e45-d6beb525884d.PNG)

Checkpoint Log:
![Logs](https://user-images.githubusercontent.com/79717068/148371839-a38132c4-d4ef-421a-a50f-ac22b1e9abc5.PNG)

Issue: When I run this playbook to check the Gaia Build I have the error on output. When I consult the Checkpoint logs, I get the right output but it gives me an error.
At ansible machine I only get an error.

Thanks!

**Comment by chkp-shirango** [comment]
Hi @BrunoJorge21,

Thanks for reaching us.
We will fix this in the next version.

Thanks,
Shiran
