### ISSUE TITLE
cp_mgmt_access_rule with inline_layer and action Apply Layer always changed on rerun

### ISSUE THREAD

**Issue by Senas23** [CheckPointSW/CheckPointAnsibleMgmtCollection#52]
Versions:
- ansible core: 2.9.27
- checkpoint_point.mgmt: 2.2.0
- python: 3.9.9

Rerunning playbook on rules with `inline_layer: <layer>`  and `action: Apply Layer`, always gives changed back. It seems after initial rule creation, the `action` API parameter's value is changed to `Inner Layer`.
I temporarily fixed the function `api_call_for_rule()` in the `check_point/mgmt/plugins/module_utils/checkpoint.py`.
Thank you!

**Comment by chkp-shirango** [comment]
Hi @Senas23,

Thanks for reaching us.
We will fix this in the next version.

Thanks,
Shiran
