### ISSUE TITLE
cp_mgmt_access_rule, rule and section name conflict, and `equals` api call bug

### ISSUE THREAD

**Issue by Senas23** [CheckPointSW/CheckPointAnsibleMgmtCollection#53]
Versions:
- ansible core: 2.9.27
- checkpoint_point.mgmt: 2.2.0
- python: 3.9.9
- SMS: R81.10 T22

Once rules are created, a subsequent run without any changes to the code and the policy has the following behavior:
- If a section and a rule name anywhere in the policy are the same, it will break with a 500 error:
```
"msg": "Checkpoint device returned error 500 with message {'message': 'Internal error. For more info search for incident [0bccfa94-1aa3-4bcf-9aaa-920695d7a36b] in log file', 'code': 'generic_internal_error'}"
```
- If a rule has any changes between the playbook and the SMS in any column but `Name`, `Position`, and `Action`, it will not update the rule. `equals` API call does not seem to see that there is a difference in the rules.

Thank you!

**Comment by chkp-shirango** [comment]
Hi @Senas23,

Thanks for reaching us.
For now please don't use the same name for rules and sections and we will fix this.
Regarding the second issue, the jumbo release with the PRJ-34081 will include this fix.

Thanks
Shiran

**Comment by chkp-edenbr** [comment]
Regarding the first issue, we require name uniqueness.
Regarding the second, the fix has been released.
