### ISSUE TITLE
add nat rule positions missing

### ISSUE THREAD

**Issue by uujonas** [CheckPointSW/CheckPointAnsibleMgmtCollection#59]
Hi,

Im trying out the cp_mgmt_add_nat_rule for creating NAT rules.
It works fine but only if I use top or bottom for the position. 
But when trying other than top or bottom I get this error: 

The invalid value [{'below': 'TEST_NAT_RULES'}] should be replaced by one of the following values: [top, bottom]

In the API reference there should also be positions for above and below:
https://sc1.checkpoint.com/documents/latest/APIs/#cli/add-nat-rule~v1.8%20

It works fine when doing it in Command Line:
add nat-rule original-source "HOST_172.16.98.101" original-destination "MGMT_SRV" translated-source "STATIC_NAT_213.50.10.100" method static package Standard position.below "TEST_NAT_RULES"

**Comment by chkp-shirango** [comment]
Hi @uujonas,

Thanks for reaching us.
We do not support the below/above parameters because it damages one of Ansible's requirements for idempotency.

Thanks
Shiran
