### ISSUE TITLE
Update documentation using position example

### ISSUE THREAD

**Issue by writememe** [CheckPointSW/CheckPointAnsibleMgmtCollection#7]
Hi Team,

Firstly, thanks for developing all these modules. Using `position: 1` throws errors so ideally this example should be changed to:  

- position: top

- position: bottom

- position: 2 or any other number other than 1

https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/blob/890a15b94de85471492fa2a3dc65dd6cd06c1648/plugins/modules/cp_mgmt_access_rule.py#L249

Cheers,
Daniel

**Comment by chkp-orso** [comment]
Thanks, 

We don't support position top/bottom because it damages one of Ansible requirements for idempotency. But we will change to position: 2 in the next version.

Thanks, Or
