### ISSUE TITLE
Is there a way to always add new access_rule or nat_rule to the bottom of the policy table?

### ISSUE THREAD

**Issue by shermannws** [CheckPointSW/CheckPointAnsibleMgmtCollection#77]
I am looking for a way to add access_rule (using `cp_mgmt_access_rule` and `cp_mgmt_add_nat_rule`) to the bottom of the policy table instead of to the top.

Adding to the top is easy as I could specify 1 to the `position` argument. However, is there an advised way to do so when adding to the bottom?

Thank you so much in advance!

**Comment by chkp-edenbr** [comment]
Hi,

The position argument can also receive the strings "top" or "bottom".

Regards,
Eden

**Comment by shermannws** [comment]
That's amazing! Thank you! @chkp-edenbr

**Comment by shermannws** [comment]
Hi @chkp-edenbr , is seems like the feature to support 'top' and 'bottom' has yet to be implemented.
Please see [source code](https://github.com/CheckPointSW/CheckPointAnsibleMgmtCollection/blob/master/plugins/module_utils/checkpoint.py#L390), lines 390 - 407.

Are there plans on releasing this feature?

**Comment by chkp-edenbr** [comment]
Hi,

We will release this feature in a future version.

Thanks,
Eden

**Comment by chkp-edenbr** [comment]
Hi,

Support for "top" and "bottom" values  for position parameter now available in new release v3.1.0.

Regards,
Eden
