### ISSUE TITLE
While adding policy package or installing policy inside, the target is not recognized. Although the target  gateway exists inside the domain. 

### ISSUE THREAD

**Issue by sasikdar** [CheckPointSW/CheckPointAnsibleMgmtCollection#88]
Hi,
I am trying to add some policy package and install it 

`- name: create domain level policy 
  check_point.mgmt.cp_mgmt_package:
    name: "{{item.name}}_LP"
    access: true
    installation_targets: my-name-musking-gateway
    threat_prevention: false
    state: present
  vars:
    ansible_checkpoint_domain: Global

- name: install domain policies
  check_point.mgmt.cp_mgmt_install_policy:
    policy_package: "{{item.name}}_LP"
    targets: my-name-musking-gateway
  vars:
    ansible_checkpoint_domain: "{{inventory_hostname}}"`

during both the tasks **"create domain level policy** " and **"install domain policies"** the target can not be recognized. I have tested it against the web_api manually with postman, and the same parameters works. 

The error message I am getting is :

fatal: _[myhost-5]: FAILED! => {"changed": false, "msg": "Checkpoint device returned error 404 with message {'code': 'generic_err_object_not_found', 'message': 'Requested object [ my-name-musking-gateway] not found'} Unpublished changes were discarded"}_

**Comment by chkp-edenbr** [comment]
Hi @sasikdar,
please upload the playbook file.
Thanks,
Eden

**Comment by sasikdar** [comment]
Hi,
It is not a bug, I had some problem on my global policies which resulted in such an error.
