### ISSUE TITLE
Not needed warning about must_change_password

### ISSUE THREAD

**Issue by bartsikkes** [CheckPointSW/CheckPointAnsibleMgmtCollection#99]
When I add an administrator via cp_mgmt_administrator* I get this warning:

[WARNING]: Module did not set no_log for must_change_password

I feel that warning is not needed here. The must_change_password variable doesn't contain any sensitive information, it is either true or false.

If you agree, can that be changed?

*) https://docs.ansible.com/ansible/latest/collections/check_point/mgmt/cp_mgmt_administrator_module.html

**Comment by chkp-edenbr** [comment]
Hi @bartsikkes ,
Thanks for notifying us, this is a warning generated from ansible regarding our module.
We will add the missing argument in the upcoming version.
Thanks,
Eden

**Comment by chkp-edenbr** [comment]
Issue fixed in our newly released version v5.0.0.
